# Colors:
# &1: Dark Blue. &2: Dark Green. &3: Dark Aqua. &4: Dark Red
# &5: Dark Purple. &6: Gold. &7: Gray. &8: Dark Gray. &9: Blue.
# &0: Black. &a: Green. &e: Yellow &d: Pink. &f: White
# Other:
# &l: Bold. &n: Underline. &o: Itallic. &k: Magic.
# &m: Strikethrough. &r: Reset.

Prefix: '&7[&cEzBroadcasts&7] ' # The space is needed at the end